### PR TITLE
Made separate file for open ports to avoid merge  conflicts 

### PR DESCRIPTION
**Pull request by pranaybathini**
Added features 
1.disconnect a node
2.list open ports and services

### CODE REVIEW

**Comment by shisen404** [comment]
Listing open ports and services is a good thing.  
This is simply a monitoring application and you don't need to kick any of the nodes out of the network (via spoofing). It is about thinking of your own idea and implementing it, spoofing technique is similar to that of kickthemout.  
I suggest you remove the spoofing part and send pull request only with your 2nd feature.

**Comment by pranaybathini** [comment]
Ok sir !!
Removed spoofing part 
Feature requested to merge
1.listing open ports and services

**Comment by shisen404** [comment]
Running your script is showing following error:  
```
Traceback (most recent call last):
  File "scanner.py", line 181, in <module>
    defaultInterface = getDefaultInterface()
  File "scanner.py", line 24, in getDefaultInterface
    network, netmask, _, interface, address,metric = max(iface_routes, key=lambda item:item[1])
ValueError: need more than 5 values to unpack  
```
I removed the metric and it worked for me. You check this thing on your own side.  
And by services, we meant services that are currently running on the node. For eg., if port number 80 and/or 443 is open then it means that Web Server is running. So basically what you need to do is provide more information regarding open ports.  
Everything else looks good.

**Comment by pranaybathini** [comment]
Sir, If I remove metric  It is showing following error
`Traceback (most recent call last):
  File "scanner.py", line 183, in <module>
    defaultInterface = getDefaultInterface()
  File "scanner.py", line 25, in getDefaultInterface
    network, netmask, _, interface, address = max(iface_routes, key=lambda item:item[1])
ValueError: too many values to unpack
`
and I have modified the code as you suggested.

**Pull request merged**
